---
- name: Retrieve Network Cards and IP Addreses
  hosts: localhost
  tasks:
    - name: Capture Network Facts
      set_fact:
        ansible_eth: "{% set ansible_eth = ansible_eth|default([]) + [hostvars[inventory_hostname]['ansible_' + item]] %}{{ ansible_eth|list }}"
      when: hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
      with_items:
        - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"

    - name: Print Network Facts
      debug:
        var: ansible_eth 

    - name: Get List of Ansible interfaces   
      set_fact:
        interfaces: "{{ hostvars[inventory_hostname]['ansible_' + item] }}"
      when: hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
      with_items:
        - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"

    - name: Print specific Facts
      debug:
        var: interfaces  
        #msg: The Device {{ ansible_eth['device'] }} has an IP address of {{ ansible_eth['ipv4']['address'] }}