---
- name: Setup Network Cards and IP Addreses
  hosts: localhost
  vars_prompt:
    - name: network_card
      prompt: Please specify the network device to configure ...
      private: false

  tasks:
    - name: Verify Network Card Information
      debug:
        msg: Preparing to configure {{ network_card }}

    - name: Configure Network Card 
      ansible.builtin.import_role:
        name: linux-system-roles.network
      vars: 
        network_provider: nm
        network_connections:
          - name: "{{ network_card }}"
            type: ethernet
            ip:
              address:
                - 192.168.0.254/24

        
      




      