---
- name: Setup System for a PXE Server
  hosts: localhost
  vars_files:
    - pxe_vars.yml
    - template_file_vars.yml

  tasks:

## Install Packages

    - name: Install Packages for PXE Boot Services
      ansible.builtin.dnf:
        name: "{{ install_packages }}"
        state: present
      become: true

##  Enable Firewall Ports and Services
    - name: Enable Firewall Services
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled 
        immediate: true 
      loop: "{{ firewall_services }}"

##  Use Jinja Template Module to create configuration

    - name: Create configuraition files
      # Comment
      ansible.builtin.template:
        src: ./{{ item.filename }}
        dest: "{{ item.destination_filename }}"
      loop: "{{ template_files }}"
    
##  Use Ansible File Modules to copy static configuration files

    - name: Copy NAMED File
      ansible.builtin.copy:
        dest: ./files/named
        src: /etc/sysconfig/named
    



## Enable Services (must be done after configuration files applied)
    - name: Enable Services 
      ansible.builtin.systemd_service:
        enabled: true
        daemon_reload:  true 
        name: "{{ item }}"
        no_block: false
        scope: system
        state: started
      loop: "{{ service_list }}"


    
