---
- name: Setup System for a PXE Server
  hosts: localhost
  vars_files:
    - pxe_vars.yml

  tasks:

## Install Packages

    - name: Install Packages for PXE Boot Services
      ansible.builtin.dnf:
        name: "{{ install_packages }}"
        state: present
      become: true

#    - name: Enable Firewall Ports and Services
    - name: Enable Firewall Services
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled 
        immediate: true 
      loop: "{{ firewall_services }}"

# Enable Services (must be done after configuration files applied)
    - name: Enable Services 
      ansible.builtin.systemd_service:
        daemon_reexec: false
        daemon_reload: false
        enabled: false
        force: false
        masked: false
        name: "{{ item }}"
        no_block: false
        scope: system
        state: reloaded
      loop: "{{ service_list }}"


    
